name: rbf_gp
network:
  hidden_units: 0  # unused
  num_layers: 0    # unused
  output_dim: 0    # unused
  activation: relu
kernel:
  initial_alpha: 1.0
  initial_beta: 0.01
  initial_eta: 1.0
  learn_priors: true
pretrain:
  enabled: true
  epochs: 1000
  lr: 0.01
  patience: 20
